### ISSUE TITLE
Folder name cannot contain forbidden characters (for window)

### ISSUE THREAD

**Issue by iseedouble** [Lam-Steven/moodle-helper#2]
Current Behavior:  
In moodle Polytechnique, if the name for the course has a forbiden character ( / \ : * ? " < > | ), the file will be saved in the download path.

Expected Behavior: 
The file is saved in the folder with the right course name.

**Comment by oyoutuon** [comment]
I'm taking this issue. :)

**Comment by hnspn** [comment]
use this regex 
```/[*?"<>|\\\/:]/g```
