### ISSUE TITLE
Imbricated files are downloaded as "view.html"

### ISSUE THREAD

**Issue by oyoutuon** [Lam-Steven/moodle-helper#7]
Current behaviour: 
Imbricated pdf files (without window-open method) are downloaded as view.html
![screenshot from 2019-02-24 23-02-05](https://user-images.githubusercontent.com/36271347/53313618-41abda00-3888-11e9-87b6-25577a429a99.png)

Expected behaviour: 
They should be downloaded as pdf files.

**Comment by Lam-Steven** [comment]
This seems to only happen on course SSH3100B.
**It is not caused by the files being imbricated**

**Comment by oyoutuon** [comment]
investigating it :)
